name: Test Action

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set Node.js 16.x
        uses: actions/setup-node@v4
        with:
          node-version: 16.x

      - name: npm install
        run: npm install

      - name: npm lint
        run: npm run check

  test:
    strategy:
      matrix:
        operating-system: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.operating-system }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set Node.js 16.x
        uses: actions/setup-node@v4
        with:
          node-version: 16.x

      - name: npm install
        run: npm install

      - name: Init Git credentials to run tests
        run: |
          git config --global user.email "me@example.com"
          git config --global user.name "Me Example"

      - name: npm test
        run: npm test
